//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARoomInterior.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best managers.
        /// </summary>
        public static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best designers.
        /// </summary>
        public static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best architects.
        /// </summary>
        public static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internet of things.
        /// </summary>
        public static string IotHeader {
            get {
                return ResourceManager.GetString("IotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сameras will give you the opportunity to sit comfortably at home, watching how the employees you hired do their job. Sensors will help you measure all the necessary indicators to ensure your future comfort. Modern data transfer devices will provide you with the opportunity to receive the necessary information in a timely manner at any time..
        /// </summary>
        public static string IotMessage {
            get {
                return ResourceManager.GetString("IotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobile app.
        /// </summary>
        public static string MobileHeader {
            get {
                return ResourceManager.GetString("MobileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our mobile application allows you to plunge into the world of augmented reality, looking at the process of designing and creating your project from a different angle. We will give the opportunity to monitor the development of the project at all stages, from the design stage, in the form of 3D models and architectural schemes, to the expected result..
        /// </summary>
        public static string MobileMessage {
            get {
                return ResourceManager.GetString("MobileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take.
        /// </summary>
        public static string Strong1 {
            get {
                return ResourceManager.GetString("Strong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Design.
        /// </summary>
        public static string Strong2 {
            get {
                return ResourceManager.GetString("Strong2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Develop.
        /// </summary>
        public static string Strong3 {
            get {
                return ResourceManager.GetString("Strong3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на you from the concept stage.
        /// </summary>
        public static string Sub11 {
            get {
                return ResourceManager.GetString("Sub11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на to an impressive result.
        /// </summary>
        public static string Sub12 {
            get {
                return ResourceManager.GetString("Sub12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на an individual interior based.
        /// </summary>
        public static string Sub21 {
            get {
                return ResourceManager.GetString("Sub21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on your lifestyle and wishes.
        /// </summary>
        public static string Sub22 {
            get {
                return ResourceManager.GetString("Sub22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на three-dimensional sketches, providing calculations,.
        /// </summary>
        public static string Sub31 {
            get {
                return ResourceManager.GetString("Sub31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на wall plans and engineering communications schemes.
        /// </summary>
        public static string Sub32 {
            get {
                return ResourceManager.GetString("Sub32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web page.
        /// </summary>
        public static string WebHeader {
            get {
                return ResourceManager.GetString("WebHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By registering on our website, you can begin to develop a project, create or add a new team, evaluate documentation requirements, conclude contracts and consult with the best specialists in their field..
        /// </summary>
        public static string WebMessage {
            get {
                return ResourceManager.GetString("WebMessage", resourceCulture);
            }
        }
    }
}
