// <auto-generated />
namespace ARoomInterior.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatespawnmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatespawnmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202008151143423_update spawn model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
